### ISSUE TITLE
Prerequisites Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by colindaven** [lucian-ilie/SAGE2#1]
Hi,

I cannot compile this and don't know which package I am missing.

Any ideas?

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 

```
/usr/include/c++/5/tuple:947:5: note:   template argument deduction/substitution failed:
./inputReader/readLoader.cpp:86:27: note:   ‘std::basic_istream<char>’ is not derived from ‘const std::tuple<_Elements ...>’
  while(getline(fin, line)>0)
                           ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/c++/5/iomanip:43,
                 from ./inputReader/readLoader.h:14,
                 from ./inputReader/readLoader.cpp:7:
/usr/include/c++/5/bits/unique_ptr.h:699:5: note: candidate: template<class _Tp, class _Dp, class _Up, class _Ep> bool std::operator>(const std::unique_ptr<_Tp, _Dp>&, const std::unique_ptr<_Up, _Ep>&)
     operator>(const unique_ptr<_Tp, _Dp>& __x,
     ^
/usr/include/c++/5/bits/unique_ptr.h:699:5: note:   template argument deduction/substitution failed:
./inputReader/readLoader.cpp:86:27: note:   ‘std::basic_istream<char>’ is not derived from ‘const std::unique_ptr<_Tp, _Dp>’
  while(getline(fin, line)>0)
                           ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/c++/5/iomanip:43,
                 from ./inputReader/readLoader.h:14,
                 from ./inputReader/readLoader.cpp:7:
/usr/include/c++/5/bits/unique_ptr.h:705:5: note: candidate: template<class _Tp, class _Dp> bool std::operator>(const std::unique_ptr<_Tp, _Dp>&, std::nullptr_t)
     operator>(const unique_ptr<_Tp, _Dp>& __x, nullptr_t)
     ^
/usr/include/c++/5/bits/unique_ptr.h:705:5: note:   template argument deduction/substitution failed:
./inputReader/readLoader.cpp:86:27: note:   ‘std::basic_istream<char>’ is not derived from ‘const std::unique_ptr<_Tp, _Dp>’
  while(getline(fin, line)>0)
                           ^
In file included from /usr/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/include/c++/5/locale:43,
                 from /usr/include/c++/5/iomanip:43,
                 from ./inputReader/readLoader.h:14,
                 from ./inputReader/readLoader.cpp:7:
/usr/include/c++/5/bits/unique_ptr.h:711:5: note: candidate: template<class _Tp, class _Dp> bool std::operator>(std::nullptr_t, const std::unique_ptr<_Tp, _Dp>&)
     operator>(nullptr_t, const unique_ptr<_Tp, _Dp>& __x)
     ^
/usr/include/c++/5/bits/unique_ptr.h:711:5: note:   template argument deduction/substitution failed:
./inputReader/readLoader.cpp:86:15: note:   cannot convert ‘std::getline<char, std::char_traits<char>, std::allocator<char> >(fin.std::basic_ifstream<char>::<anonymous>, line)’ (type ‘std::basic_istream<char>’) to type ‘std::nullptr_t’
  while(getline(fin, line)>0)
               ^
makefile:50: recipe for target 'matePair.o' failed
make: *** [matePair.o] Error 1
make: *** Waiting for unfinished jobs....
makefile:29: recipe for target 'readLoader.o' failed
make: *** [readLoader.o] Error 1
```

**Comment by mmolnar2** [comment]
Hi,

It looks as though the problem is with the IO Manipulators from the compiler.  We have not tested using gcc version 5 or above.  You could try compiling with an earlier version of gcc.  If that does not work then send another message.

Thanks,

Mike

**Comment by colindaven** [comment]
The only older system I have is SLES11.1 - very old.

Its not happy here either. A precompiled - ideally bioconda - version would be fantastic to facilitate usage ...



```

SAGE2> gcc --version
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]


make -j 24
g++ -fopenmp -std=c++0x -O3 -W -Wall  -o readLoader.o -c ./inputReader/readLoader.cpp
g++ -fopenmp -std=c++0x -O3 -W -Wall  -o matePair.o -c ./matePair/matePair.cpp
./matePair/matePair.cpp: In constructor ‘MatePair::MatePair(OverlapGraph*, ReadLoader*)’:
./matePair/matePair.cpp:28: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp: In destructor ‘MatePair::~MatePair()’:
./matePair/matePair.cpp:37: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp:54: warning: iteration variable ‘i’ is unsigned
./inputReader/readLoader.cpp: In destructor ‘ReadLoader::~ReadLoader()’:
./inputReader/readLoader.cpp:65: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp: In member function ‘void MatePair::processMatePairs(std::deque<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, int)’:
./matePair/matePair.cpp:169: error: ‘readsArray’ is predetermined ‘shared’ for ‘shared’
./matePair/matePair.cpp:172: warning: iteration variable ‘i’ is unsigned
./inputReader/readLoader.cpp: In member function ‘void ReadLoader::organizeReads()’:
./inputReader/readLoader.cpp:250: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp: In member function ‘void MatePair::computeMeanSD(int, int, int, int*, int*)’:
./matePair/matePair.cpp:335: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp: In member function ‘void MatePair::mapReadsToEdges()’:
./matePair/matePair.cpp:398: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp:407: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp:425: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp:464: warning: iteration variable ‘i’ is unsigned
./matePair/matePair.cpp: In member function ‘void MatePair::mapReadLocations()’:
./matePair/matePair.cpp:502: warning: iteration variable ‘i’ is unsigned
/usr/include/c++/4.3/parallel/algo.h: In function ‘void std::__parallel::sort(_RAIter, _RAIter) [with _RAIter = Read*]’:
./inputReader/readLoader.cpp:221:   instantiated from here
/usr/include/c++/4.3/parallel/algo.h:1736: error: call of overloaded ‘sort(Read*&, Read*&, std::less<Read>)’ is ambiguous
/usr/include/c++/4.3/parallel/algo.h:1741: note: candidates are: void std::__parallel::sort(_RAIter, _RAIter, _Compare) [with _RAIter = Read*, _Compare = std::less<Read>]
/usr/include/c++/4.3/bits/stl_algo.h:4806: note:                 void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = Read*, _Compare = std::less<Read>]
make: *** [matePair.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [readLoader.o] Error 1

```

**Comment by mmolnar2** [comment]
Hi Colin,

Sorry for the late reply.  I tested it with gcc 4.3.4 and received the same error.  It will compile with version gcc 4.9.2, and probably most gcc versions above 4.8.  I do not have access to many systems so a precompiled version from my machine would probably not work.

Mike

**Comment by colindaven** [comment]
Hi Mike,

Maybe it would make sense to put this into bioconda so people can use it without having to compile it ? Would certainly increase uptake, but require more time on your side unfortunately. At the moment I don't have access to a gcc4.9.2 system.

cheers,
Colin

**Comment by mmolnar2** [comment]
Hi Colin,

SAGE2 is now available through conda:

conda install -c mmolnar sage2

Cheers,

Mike

**Comment by colindaven** [comment]
Hi Mike,
thanks for this, I'll give is a go.
Colin

**Comment by th-of** [comment]
Change the flag to g++11 and it compiles just fine, at least on Fedora 29.
